### ISSUE TITLE
Weird behaviour on ManyToMany field

### ISSUE THREAD

**Issue by yanikkoval** [rbarrois/factory_boy#315]
I know you don't support [Djangae](https://github.com/potatolondon/djangae), but there may be some useful information for you to dig :)

https://github.com/potatolondon/djangae/issues/717

**Comment by rbarrois** [comment]
Thanks for the input!

The comment on that issue is spot-on: djangae seems to expect you to call ``.save()`` after using ``.add()``.

If you use factory_boy's ``post_generation`` hooks, the ``DjangoModelFactory`` base will perform a post-post-generation save as seen in https://github.com/rbarrois/factory_boy/blob/master/factory/django.py#L183.

For a more thorough example, you could find some help here: http://factoryboy.readthedocs.io/en/latest/recipes.html#simple-many-to-many-relationship

Hopefully, this will help future users ;)
