### ISSUE TITLE
How to get dict dump of Factory

### ISSUE THREAD

**Issue by malicustommade** [rbarrois/factory_boy#68]
Hello,

I need to get a full dump of a Factory as a dict so that I can serialize it to json. `FactoryName.attributes()` works great except when there is a `SubField`, in which case it evaluates it and returns an instantiated version of the object as opposed to a dictionary of key: value of the `SubField` attributes.

I tried to hack around this by traversing the `Factory` myself but it turns out that I'll have to duplicate a lot of code that already exists. Do you see an easy way to do this?

**Comment by jeffwidman** [comment]
I've also got some JSON API's that I'd like to test by `POST`ing sample data creating using my factories.

I tried:

    c1 = GearCategoryFactory.stub(parent=0)
    response = client.post(
            url_for('api.api_new_gear_category'),
            headers=json_headers,
            data=json.dumps(c1))

and unsurprisingly got `TypeError: <factory.containers.StubObject object at 0x112904fd0> is not JSON serializable`.

I tried calling `json.dumps(dict(c1))` but got `TypeError: 'StubObject' object is not iterable`.

Probably the simplest solution here is adding an extra `dict` strategy as suggested in #147.

Would also be nice if it supported on-the-fly exclusion of fields that are normally created as part of the stub--for example: 

Option 1, preferred because less verbose, but 'exclude' becomes a keyword that can't be easily used as a field name:

    c1 = GearCategoryFactory.stub(parent=0, exclude=[image, other_field])

Option 2:

    c1 = GearCategoryFactory.stub(parent=0, image=exclude, other_field=exclude)

**Comment by jeffwidman** [comment]
Thinking about this more, an open question here is how to serialize attributes that are sometimes object references to other factories? 

In my case of `POST`ing individual items to an API, I'm always specifying these attributes as the PK ID of a pre-existing DB object, so best solution try to serialize to an int. If this throws an exception, just catch the exception and try serializing to a string (for example if someone is using UUIDs rather than numeric IDs for PKs).

I'm sure there are times people will want to stub out groups of objects, including references between them, and then serialize the entire group... However, it's actually impossible to maintain a reference between them during the serialization process if the related factories aren't already committed to the DB... there's no PK assigned for the related object at the time of serialization. 

So perhaps simply be default trying to serialize any foreign factory object references to the PK is the best strategy here. If the PK is specified by the user, serialize that. It it's not, then the PK won't have been assigned by the DB yet, and should simply serialize to the equivalent of `None`/`null`.

**Comment by rbarrois** [comment]
@jeffwidman Well, serializing complex stacks of objects is the job of a proper serializer (either the json one, or more advanced frameworks).

However, it is relatively easy to convert the output of a factory to a dict, as displayed in the 2 related commits.

What do you think? Should we go further and provide an official shortcut for this?

**Comment by jeffwidman** [comment]
Just got a chance to look at it. Recipe looks perfect, nice job!

**Comment by BigChief45** [comment]
@rbarrois 

I am testing the `factory.build(dict, FACTORY_CLASS=MyFactory)`. However the Foreign Key (`factory.SubFactory()`) fields contain a reference to an instance of an object, created through its factory. I think it would be better if this would return the ID of this object instead.

Is there any built-in method that does this?

**Comment by hectorcanto** [comment]
The factory.build(dict, FACTORY_CLASS=MyFactory) idea does not works with factory.Sequence, I'm alway getting a 0.

What about:
```python
MyDictFactory = lambda: MyFactory.stub().__dict__
```

**Comment by hectorcanto** [comment]
My previous example does not work when introducing keywords. I kept working on it and got to:
```
from functools import partial

def dict_factory(factory, **kwargs): 
    return factory.stub(**kwargs).__dict__ 

UserDictFactory = partial(dict_factory, UserFactory))
```
I hope it is useful

**Comment by chanyou0311** [comment]
@hectorcanto 
Great way!

I used that code as a reference and created a function that also outputs SubFactory as a dict.

```python3
from functools import partial
from typing import Any, Dict

from factory import Factory
from factory.base import StubObject


def generate_dict_factory(factory: Factory):
    def convert_dict_from_stub(stub: StubObject) -> Dict[str, Any]:
        stub_dict = stub.__dict__
        for key, value in stub_dict.items():
            if isinstance(value, StubObject):
                stub_dict[key] = convert_dict_from_stub(value)
        return stub_dict

    def dict_factory(factory, **kwargs):
        stub = factory.stub(**kwargs)
        stub_dict = convert_dict_from_stub(stub)
        return stub_dict

    return partial(dict_factory, factory)

# example of usage
UserDictFactory = generate_dict_factory(UserFactory)
```

We look forward to helping you.

**Comment by Kirill-Shklyarenko** [comment]
@chanyou0311 
I have `TypeError: Object of type partial is not JSON serializable`
 when try to put UserDictFactory
```
UserDictFactory = generate_dict_factory(UserFactory)
request = self.client.put(url, UserDictFactory, format='json')
```
I find this solution and it works for me:
```
def to_dict(instance):
    opts = instance._meta
    data = {}
    for f in chain(opts.concrete_fields, opts.private_fields):
        data[f.name] = f.value_from_object(instance)
    for f in opts.many_to_many:
        data[f.name] = [i.id for i in f.value_from_object(instance)]
    return data
```
